CLOUD-811 added paymentSessionId as optional query param to list intr…
w-pay/oas-wpay pull request #12
Opened 2021-09-08 00:45 UTC by lohithv

2021-09-20 03:40 UTC, mchopra-woolworths approved these changes

2021-09-20 04:36 UTC, mchopra-woolworths requested changes
1.0.7 is already in master. New version has to be created with 1.0.8

2021-09-20 04:37 UTC, mchopra-woolworths commented on src/wpay-1.json
> +    "version":"1.0.7"
@lohithv - Hey Lohith, there is already a version of 1.0.7 in master. Please uplift this change to 1.0.8

2021-09-23 01:46 UTC, lohithv commented on src/wpay-1.json
> +    "version":"1.0.7"
@mchopra-woolworths done

2021-09-28 04:21 UTC, JamesMBligh requested changes
v1.0.7 has been amended since this PR was raised to deal with some EDPay changes.  This won't affect wpay-1.json as it will be merged but it will affect wpay-1-0-8.json as the changes won't be merged.

Could you back merge from master then we can approve the PR.

2021-09-28 06:27 UTC, lohithv commented
> v1.0.7 has been amended since this PR was raised to deal with some EDPay changes. This won't affect wpay-1.json as it will be merged but it will affect wpay-1-0-8.json as the changes won't be merged.
> 
> Could you back merge from master then we can approve the PR.

@JamesMBligh done

2021-12-01 06:03 UTC, merged